services:
  mapper:
    container_name: MIA_bev
    build: .
    restart: unless-stopped
    shm_size: "16g"
    ipc: host

    volumes:
      - .:/workspace
      - ./datasets:/workspace/datasets

    tty: true
    stdin_open: true
    gpus: all

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - PYTHONUNBUFFERED=1
      - DEBIAN_FRONTEND=noninteractive

    command: bash 
